name: CI - build and test
on:
  push:
    branches: [ main ]
jobs:
   build:                           
      runs-on: ubuntu-latest         
      steps:    
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v6        
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew              

      - name: Build and test
        working-directory: .
        run: ./gradlew build 

      - name: Generate Reports for Website and Deploy
        working-directory: .
        run: |
          eval $(ssh-agent -s -t 600)
          ssh-add <(echo "${{ secrets.REPORTS_SSH_KEY }}")
          git config --global user.email "bbows001@odu.edu"
          git config --global user.name "Project Actions"
          ./gradlew deployReports

